services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.16.1
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - http.host=0.0.0.0
      - transport.host=0.0.0.0
      - xpack.security.enabled=false
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xmx1024m -Xms1024m"
    networks:
      - elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - esdata:/usr/share/elasticsearch/data
      - ./conf/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml

  kibana:
    image: docker.elastic.co/kibana/kibana:8.16.1
    restart: always
    ports:
      - "5601:5601"
    networks:
      - elasticsearch
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - ./conf/kibana.yml:/usr/share/kibana/config/kibana.yml
    links:
      - elasticsearch
    depends_on:
      - elasticsearch

networks:
  elasticsearch:
    driver: bridge
    name: elasticsearch

volumes:
  esdata:
    driver: local
    name: esdata
